version: "2"

linters:
  enable:
    - errcheck
    - govet
    - revive
    - staticcheck
    - ineffassign
    - misspell
  settings:
    revive:
      rules:
        - name: exported
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
