ARG GO_IMAGE=golang:1.25.1-alpine3.22@sha256:b6ed3fd0452c0e9bcdef5597f29cc1418f61672e9d3a2f55bf02e7222c014abd
FROM ${GO_IMAGE} AS build

WORKDIR /src
COPY go.mod go.sum ./
COPY vendor ./vendor
COPY cmd ./cmd
COPY internal ./internal
RUN CGO_ENABLED=0 GOOS=linux go build -mod=vendor -trimpath -ldflags="-s -w" -o /out/cloudattrib ./cmd/cloudattrib

FROM scratch
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=build /out/cloudattrib /usr/local/bin/cloudattrib
USER 65532:65532
ENTRYPOINT ["/usr/local/bin/cloudattrib"]
CMD ["serve", "--config", "/etc/cloudattrib/config.yaml"]
